### ISSUE TITLE
Exception: OrderPayments.Expires is the incorrect type

### ISSUE THREAD

**Issue by BlackcatSW** [mivaecommerce/api-sdk-csharp#1]
An exception error is bubbling up to OrderListLoadQueryResponse.  The when the response from OrderListLoad is Deserialized by BaseClient, the JSON parser claims OrderPayments.Expires is the incorrect type and is defined as a String. The debugger shows Expires in an Int32.

Made a couple of type changes and attached a patch.

VS2022E 17.3 P4, .NET 7.0

[OrderPayments.patch.gz](https://github.com/mivaecommerce/api-sdk-csharp/files/9161036/OrderPayments.patch.gz)
.

**Comment by ghassani** [comment]
Thank you for reporting the issue. I have created a bug for this in our internal tracker. It has been assigned to bug **MMAPI-60**. If a fix is deemed required then you can expect it to be included with the next minor release.
