### ISSUE TITLE
BaseClient.SendRequest JSON exception error. Unknown property 'discounts'

### ISSUE THREAD

**Issue by BlackcatSW** [mivaecommerce/api-sdk-csharp#2]
The OrderItemOption class is missing a discounts class.

Attached zip includes new OrderItemOptionDiscounts.cs, a tweaked OrderItemOption.cs, and a test JSON file created from one of our stores.

[items_options_discounts.zip](https://github.com/mivaecommerce/api-sdk-csharp/files/9174838/items_options_discounts.zip)

**Comment by ghassani** [comment]
Thank you for reporting the issue. Bug has been created in our internal tracker. Reference **MMAPI-61**
